export const tuning = {
  // Core simulation
  pixelsPerMeter: 36, // 36 pixels = 1 meter; this is used for physics scaling and general size reference.
  fixedStepSeconds: 1 / 60, // The physics simulation runs at a fixed timestep for stability; this is the duration of each step in seconds.

  // Debug & input
  debugToggleKey: 'TAB',

  // World layout
  worldHexSize: 144,
  worldCellInset: 15,
  initialWorldRadius: 1,

  // World progression
  growthPickupsPerSegment: 50,
  // The first world expansion uses this threshold; each next stage adds expansionThresholdStep.
  initialExpansionThreshold: 20,
  expansionThresholdStep: 100,

  // Myriapoda body
  initialSegments: 4,
  maxSegments: 30,
  segmentSpacing: 29,
  headToBodyOffsetPx: 15,
  segmentRadiusStart: 10,
  segmentRadiusEnd: 7,
  bodyAlpha: 0.26,
  headSpriteScale: 2.6,
  myriapodaBodyCircleScale: 1.3,
  myriapodaHeadVisualScale: 1.5,
  myriapodaMustacheLengthScale: 1.45,
  myriapodaHeadColor: 0xaee7c0,
  myriapodaHeadOutlineColor: 0xe6fff1,
  myriapodaStomachColor: 0xffaecd,
  limbBaseColor: 0xaee7c0,
  limbGlowColor: 0xfff3ac,

  // Head movement
  headRadius: 6,
  headThreatRadius: 22,
  moveSpeed: 4.1,
  moveAcceleration: 0.14,
  moveDeceleration: 0.01,
  turnLerp: 0.18,
  headLinearDamping: 4.6,
  headAngularDamping: 8,
  maxSpeed: 4.1,

  // Vacuum & pickup handling
  vacuumConeLength: 96,
  absorbRadius: 14,
  headEatConeHalfAngle: 0.7,
  vacuumSuctionLerp: 0.16,
  vacuumPickupCountForMaxSuction: 3,
  vacuumConsumePulseSeconds: 0.18,
  vacuumWispWidth: 2.4,
  vacuumWispAlpha: 0.28,
  mouthConsumeBoost: 0.58,
  pickupVacuumForce: 4.5,
  pickupLinearDamping: 4.4,

  // Camera
  cameraLerp: 0.085,
  cameraLookAhead: 9,
  cameraMotionZoomOut: 0.022,
  cameraZoomDecay: 0.14,
  cameraShakeDecay: 0.16,
  cameraPreferredZoom: 1,
  cameraAbsoluteMinZoom: 0.24,
  cameraAbsoluteMaxZoom: 1.07,
  cameraFitPaddingPx: 178,
  cameraWheelStep: 0.12,
  cameraWheelMinFactor: 0.75,
  cameraWheelMaxFactor: 1.45,
  cameraPickupZoom: 0.01,
  cameraPickupShake: 0.3,
  cameraHitZoom: 0.014,
  cameraHitShake: 0.65,
  cameraExpansionZoom: 0.032,
  cameraExpansionShake: 1.35,

  // UI
  uiPanelMinWidth: 240,
  uiPanelMaxWidth: 280,
  uiPanelMarginTop: 18,
  uiPanelMarginRight: 20,
  uiCounterIconSize: 24,
  uiHeaderPillWidth: 88,
  uiHeaderPillHeight: 32,
  uiPanelAccentColor: 0x9fdfff,
  uiDangerColor: 0xff6d78,

  // World rendering
  worldBorderBaseWidth: 8,
  worldBorderProgressWidth: 10,
  worldBorderGlowWidth: 4,
  worldCellShadowInset: 4,
  worldCellInnerInset: 11,
  worldCellBaseFillAlpha: 0.34,
  worldCellPulseSpeed: 1.15,
  worldCellHighlightTravelSpeed: 0.9,
  worldCellReactiveFillAlpha: 0.16,
  worldCellReactiveGlowAlpha: 0.1,
  worldCellContourAlpha: 0.13,
  worldCellPlayerInfluenceRadiusMultiplier: 1.8,
  worldCellPlayerGlowAlpha: 0.18,
  worldFillPulseDecay: 1.4,
  worldFillDisplayLerp: 0.12,
  worldBorderTrailWindow: 0.2,
  worldBorderFrontWindow: 0.045,
  expansionAnimationSeconds: 3.6,
  worldStageSpacingBreath: 0.11,
  worldRevealCellMinScale: 0.36,

  // World border (GPU bloom on progress outline)
  worldBorderBloomThreshold: 0.24,
  worldBorderBloomRadius: 18,
  worldBorderBloomSteps: 4,
  worldBorderBloomAmount: 0.92,

  // Myriapoda FX
  myriapodaFxShellShadowColor: 0x16352e,
  myriapodaFxShellShadowAlpha: 0.22,
  myriapodaFxShellHighlightColor: 0xf1fff7,
  myriapodaFxShellHighlightAlpha: 0.11,
  myriapodaFxShellSpecColor: 0xffffff,
  myriapodaFxShellSpecAlpha: 0.08,
  myriapodaFxStomachGradientInnerColor: 0xfff1c3,
  myriapodaFxStomachGradientOuterColor: 0xff8eb9,
  myriapodaFxStomachGradientAlpha: 0.34,
  myriapodaFxStomachNoiseAlpha: 0.18,
  myriapodaFxStomachNoiseCellsX: 5,
  myriapodaFxStomachNoiseCellsY: 4,
  myriapodaFxStomachNoiseIterations: 2,
  myriapodaFxStomachNoiseWarpAmount: 0.14,
  myriapodaFxStomachNoiseFlowSpeed: 0.28,
  myriapodaFxStomachNoiseOffsetSpeedX: 0.018,
  myriapodaFxStomachNoiseOffsetSpeedY: -0.012,
  myriapodaFxStomachMaskBlurRadius: 10,
  myriapodaFxStomachMembraneGlowColor: 0xff8dbb,
  myriapodaFxStomachMembraneGlowAlpha: 0.2,
  myriapodaFxStomachMembraneInnerAlpha: 0.48,
  myriapodaFxStomachParticleGlowAlpha: 0.16,
  myriapodaFxVacuumGlowColor: 0xc8fff7,
  myriapodaFxVacuumGlowAlpha: 0.22,
  myriapodaFxVacuumCoreAlpha: 0.48,
  myriapodaFxVacuumBloomThreshold: 0.18,
  myriapodaFxVacuumBloomRadius: 14,
  myriapodaFxVacuumBloomSteps: 4,
  myriapodaFxVacuumBloomAmount: 0.64,

  // Status UI FX
  statusFxChamberGradientTopColor: 0x13343e,
  statusFxChamberGradientBottomColor: 0x2f7d8f,
  statusFxChamberGradientAlpha: 0.3,
  statusFxChamberNoiseAlpha: 0.16,
  statusFxChamberNoiseCellsX: 4,
  statusFxChamberNoiseCellsY: 5,
  statusFxChamberNoiseIterations: 2,
  statusFxChamberNoiseWarpAmount: 0.12,
  statusFxChamberNoiseFlowSpeed: 0.18,
  statusFxChamberNoiseOffsetSpeedX: 0.012,
  statusFxChamberNoiseOffsetSpeedY: -0.01,
  statusFxChamberMaskBlurRadius: 8,
  statusFxChamberGlassAlpha: 0.12,
  statusFxChamberGlowAlpha: 0.18,
  statusFxChamberParticleGlowAlpha: 0.12,
  statusFxChamberDangerWashAlpha: 0.16,

  // Transition FX
  transitionFxDurationMs: 950,
  transitionFxGradientTopColor: 0xd2fbff,
  transitionFxGradientBottomColor: 0xffc98b,
  transitionFxGradientAlpha: 0.38,
  transitionFxNoiseAlpha: 0.22,
  transitionFxNoiseCellsX: 6,
  transitionFxNoiseCellsY: 5,
  transitionFxNoiseIterations: 2,
  transitionFxNoiseWarpAmount: 0.16,
  transitionFxNoiseFlowSpeed: 0.4,
  transitionFxNoiseOffsetSpeedX: 0.03,
  transitionFxNoiseOffsetSpeedY: -0.02,
  transitionFxFlashAlpha: 0.24,
  transitionFxWipeSoftness: 0.18,

  // Enemies & hostile pickups
  targetEnemyCount: 2,
  enemyCap: 10,
  enemySpawnRadiusPadding: 40,
  enemyChaseForce: 0.9,
  enemyMaxSpeed: 1.2,
  enemyLinearDamping: 8.4,
  enemyAngularDamping: 11,
  enemyRadius: 12.2,
  enemyDisplaySize: 22.8,
  enemyHealth: 1,
  enemyShardScale: 1,
  parasiteDropChance: 0.15,
  parasiteLifetimeSeconds: 20,
  parasiteConsumeIntervalSeconds: 2,

  // Limb combat
  limbCount: 4,
  limbLinks: 4,
  limbLinkLengthPx: 6,
  limbThicknessPx: 2,
  limbCooldownSeconds: 0.35,
  limbAttackIntervalSeconds: 3,
  limbAttackConeRangePx: 56,
  limbAttackConeHalfAngle: Math.PI / 4,
  limbRestReachPx: 8,
  limbAttackExtendPx: 22,
  limbExtendSeconds: 0.78,
  limbHitSeconds: 0.2,
  limbRetractSeconds: 0.74,
  limbWhipCurvePx: 13,
  limbSwayPx: 4,
  limbRootPull: 30,
  limbChainPull: 15,
  limbRecoveryPullBoost: 1.45,
  limbHomeSnapDistancePx: 2.2,
  limbDamage: 1,

  // Plants
  purifiedPlantOccupancyChance: 0.8,
  plantVacuumForce: 4.4,
  plantGatherRadiusPx: 28,
  plantHexSpawnRadiusXPx: 36,
  plantHexSpawnRadiusYPx: 26,
  plantRootOffsetYPx: 18,
  plantDropScatterForceMin: 0.08,
  plantDropScatterForceMax: 0.18,
  plantDropScatterDistanceMin: 6,
  plantDropScatterDistanceMax: 14,
  fiberPlantCooldownSeconds: 18,
  fiberPlantChewSeconds: 0.85,
  fiberPlantRegrowSeconds: 1.8,
  fiberPlantSegmentLengthPx: 10,
  fiberPlantStemCount: 3,
  fiberPlantTopRadiusPx: 5.8,
  fiberPlantStemRadiusPx: 3.2,
  fiberPlantReturnForce: 3.7,
  fiberPlantUpperVacuumForceScale: 1.55,
  fiberPlantMidVacuumForceScale: 1.02,
  fiberPlantLowerVacuumForceScale: 0.52,
  fiberPlantBaseGrowthScale: 0.28,

  // Tail
  tailLengthPx: 30,
  tailRadiusPx: 3.2,
  tailMotorForce: 2.8,
  tailMotorTorque: 1.6,
  tailCorrectionFactor: 0.38,
  tailSwayPx: 8,

  // Stomach
  stomachRadiusMeters: 0.64,
  stomachContainmentMarginMeters: 0.04,
  stomachParticleLimit: 100,
  stomachMixerAngularSpeed: 1.4,
} as const;
