import {
  BG_COLORS,
  BIO_COLORS,
  DEAD_COLORS,
  PARTICLE_COLORS,
} from '@/background/palette';

export const tuning = {
  // Core simulation
  pixelsPerMeter: 36, // 36 pixels = 1 meter; this is used for physics scaling and general size reference.
  fixedStepSeconds: 1 / 60, // The physics simulation runs at a fixed timestep for stability; this is the duration of each step in seconds.

  // Debug & input
  debugToggleKey: 'TAB',

  // World layout
  worldHexSize: 144,
  worldCellInset: 15,
  initialWorldRadius: 1,

  // World progression
  // The first world expansion uses this threshold; each next stage adds expansionThresholdStep.
  initialExpansionThreshold: 20,
  expansionThresholdStep: 100,

  // Myriapoda body
  initialSegments: 4,
  maxSegments: 30,
  segmentSpacing: 29,
  headToBodyOffsetPx: 15,
  segmentRadiusStart: 10,
  segmentRadiusEnd: 7,
  bodyAlpha: 0.26,
  headSpriteScale: 2.6,
  myriapodaBodyCircleScale: 1.3,
  myriapodaHeadVisualScale: 1.5,
  myriapodaMustacheLengthScale: 1.45,
  myriapodaHeadColor: 0xaee7c0,
  myriapodaHeadOutlineColor: 0xe6fff1,
  myriapodaStomachColor: 0xffaecd,
  myriapodaDamageFlashColor: 0xff4d5e,
  myriapodaDamageFlashSeconds: 0.72,
  myriapodaDamageBlinkSpeed: 20,
  myriapodaDamageBurstSeconds: 0.54,
  limbBaseColor: 0xaee7c0,
  limbGlowColor: 0xfff3ac,
  limbElectricGlowColor: 0x49d9ff,
  limbElectricMidColor: 0xa9f3ff,
  limbElectricCoreColor: 0xffffff,
  limbElectricFlashColor: 0xdaf8ff,

  // Head movement
  headRadius: 6,
  headThreatRadius: 22,
  moveSpeed: 4.1,
  moveAcceleration: 0.14,
  moveDeceleration: 0.01,
  turnLerp: 0.18,
  headLinearDamping: 4.6,
  headAngularDamping: 8,
  maxSpeed: 4.1,
  dashCooldownSeconds: 10,
  dashActiveSeconds: 0.72,
  dashMotionSeconds: 1.1,
  dashShakeSeconds: 0.34,
  dashSpeed: 7.4,
  dashGlideSpeed: 5.2,
  dashVelocityCarry: 0.48,
  dashVelocityLerp: 0.34,
  dashShakeAmplitudePx: 6.8,
  dashWaveAmplitudeStomachPx: 1.08,
  dashWaveAmplitudeTailPx: 2.24,
  dashWaveFrequency: 7.2,
  dashWaveTravel: 4.8,
  dashCameraZoom: 0.028,
  dashCameraShake: 0.92,
  dashFxWhirlTailOffsetPx: 10,
  dashFxWhirlMotionOffsetPx: 12,
  dashFxLineShadowColor: 0x8a9aa4,
  dashFxLineCoreColor: 0x5ee7ff,
  dashFxLineHighlightColor: 0xeaffff,
  dashFxLineTravelSpeed: 1.8,
  dashFxLinePulseSpeed: 8.4,
  dashFxLinePulseAmount: 0.16,
  dashFxLineGlowWidthBoost: 1.55,
  dashFxLineHighlightLength: 0.34,
  dashFxChevronLengthPx: 5.4,
  dashFxChevronWidthPx: 2.8,
  dashFxBackLineSpacingPx: 7,
  dashFxBackLineLengthPx: 28,
  dashFxBackLineLeadPx: 11,
  dashFxSideLineCount: 3,
  dashFxSideLineBaseOffsetPx: 8,
  dashFxSideLineTailOffsetPx: 16,
  dashFxSideLineLengthPx: 24,
  dashFxSideLineLeadPx: 9,
  dashFxBloomThreshold: 0.16,
  dashFxBloomRadius: 14,
  dashFxBloomSteps: 4,
  dashFxBloomAmount: 0.72,

  // Vacuum & pickup handling
  vacuumConeLength: 96,
  absorbRadius: 14,
  headEatConeHalfAngle: 0.7,
  vacuumSuctionLerp: 0.16,
  vacuumPickupCountForMaxSuction: 3,
  vacuumConsumePulseSeconds: 0.18,
  vacuumWispWidth: 2.4,
  vacuumWispAlpha: 0.28,
  mouthConsumeBoost: 0.58,
  pickupVacuumForce: 4.5,
  pickupLinearDamping: 4.4,

  // Camera
  cameraLerp: 0.085,
  cameraLookAhead: 9,
  cameraMotionZoomOut: 0.022,
  cameraZoomDecay: 0.14,
  cameraShakeDecay: 0.16,
  cameraPreferredZoom: 1,
  cameraAbsoluteMinZoom: 0.24,
  cameraAbsoluteMaxZoom: 1.07,
  cameraFitPaddingPx: 178,
  cameraWheelStep: 0.12,
  cameraWheelMinFactor: 0.75,
  cameraWheelMaxFactor: 1.45,
  cameraPickupZoom: 0.01,
  cameraPickupShake: 0.3,
  cameraHitZoom: 0.014,
  cameraHitShake: 0.65,
  cameraExpansionZoom: 0.032,
  cameraExpansionShake: 1.35,
  /** Subtracted from camera zoom at expansion start; fades out over `expansionLeadOutFraction` of the timeline (pull back before the spin). */
  cameraExpansionLeadOutZoom: 0.04,
  /** Portion [0,1] of expansion over which `cameraExpansionLeadOutZoom` eases from full to zero. */
  expansionLeadOutFraction: 0.2,
  /**
   * During stage expansion, zoom is blended from normal fit zoom toward `cameraAbsoluteMinZoom`.
   * 0 = keep auto-fit only; 1 = full zoom-out to the absolute floor (aggressive).
   */
  cameraExpansionZoomOutBlend: 0.34,
  /** Scroll smoothing while expansion pins the view on world center (higher = quicker centering). */
  cameraExpansionFollowLerp: 0.26,
  /** Scales expansion-driven shake so the map stays steadier in frame. */
  cameraExpansionShakeScale: 0.3,

  // UI
  uiPanelMinWidth: 240,
  uiPanelMaxWidth: 280,
  uiPanelMarginTop: 18,
  uiPanelMarginRight: 20,
  uiCounterIconSize: 24,
  uiHeaderPillWidth: 100,
  uiHeaderPillHeight: 42,
  uiPanelAccentColor: 0x9fdfff,
  uiDangerColor: 0xff6d78,

  // Background
  background: {
    palette: {
      bg: BG_COLORS,
      bio: BIO_COLORS,
      dead: DEAD_COLORS,
      particles: PARTICLE_COLORS,
    },
    parallax: {
      layer1: 0.08,
      layer2: 0.16,
      farDust: 0.22,
      spores: 0.28,
      nearMotes: 0.35,
      layer4: 0.12,
    },
    /** All abyss `depths` must stay below `worldHexBaseDepth` so the hex grid draws on top. */
    depths: {
      layer1: 0.04,
      layer4Far: 0.08,
      /** Sits under main tissue webs; same texture, capillary tint. */
      layer2Capillary: 0.118,
      layer2: 0.14,
      farDust: 0.18,
      layer4Near: 0.22,
      spores: 0.28,
      /** Larger soft particles drifting through the depth field (between spores and near motes). */
      bioFloat: 0.605,
      nearMotes: 0.72,
      overlayBase: 0.36,
      overlayTissue: 0.31,
      overlayDust: 0.36,
    },
    alpha: {
      layer1CloudMin: 0.12,
      layer1CloudMax: 0.2,
      layer1Vignette: 0.07,
      tissueWebMin: 0.2,
      tissueWebMax: 0.28,
      membraneMin: 0.06,
      membraneMax: 0.14,
      corruptionMin: 0.08,
      corruptionMax: 0.18,
      crackMin: 0.1,
      crackMax: 0.18,
      overlayCloudMin: 0.08,
      overlayCloudMax: 0.14,
      overlayTissueMin: 0.04,
      overlayTissueMax: 0.09,
    },
    motion: {
      layer1DriftPxPerSecond: 3.2,
      layer2DriftPxPerSecond: 4.8,
      layer4DriftPxPerSecond: 2.6,
      overlayDriftPxPerSecond: 2.4,
      breatheMinSeconds: 4,
      breatheMaxSeconds: 8,
      corruptionPulseMinSeconds: 5,
      corruptionPulseMaxSeconds: 9,
      rareFlickerMinSeconds: 6,
      rareFlickerMaxSeconds: 14,
    },
    particles: {
      farDustMax: 130,
      farDustFrequencyMs: 155,
      /** Dense global fill; emit zone covers full backdrop coverage. */
      sporesMax: 150,
      sporesFrequencyMs: 82,
      /** Mid-layer soft bio drifters (full spore zone). */
      bioFloatMax: 48,
      bioFloatFrequencyMs: 125,
      nearMotesMax: 28,
      nearMotesFrequencyMs: 640,
      livingAccentMax: 28,
      livingAccentFrequencyMs: 360,
      overlayDustMax: 52,
      overlayDustFrequencyMs: 300,
      overlayGlowMax: 22,
      overlayGlowFrequencyMs: 420,
    },
    coverage: {
      gameplayWidthMultiplier: 1.9,
      gameplayHeightMultiplier: 1.9,
      overlayWidthMultiplier: 1.12,
      overlayHeightMultiplier: 1.12,
      minimumWorldSizePx: 1500,
      viewportHalfCoverMultiplier: 1.22,
      viewportRadialCoverMultiplier: 1.18,
    },
    /** Backdrop anchor: blend world center toward player (matches hex world at origin). */
    layer1FocusBias: 0.88,
    /** Tiled bio-web texture across the full coverage rect (cols×rows instances). */
    tissueWebGrid: { cols: 6, rows: 5 },
    tissueWebBaseSizeFactor: 0.26,
    /** Applied to final tile width/height (lower = thinner, more filigree). */
    tissueWebTileScale: 0.52,
    /** Minimum visibility for web tiles in low-bio areas (still read as “filled”). */
    tissueWebAlphaFloor: 0.12,
    /** Finer reddish vascular layer (staggered grid, drawn below main webs). */
    tissueWebCapillaryGrid: { cols: 7, rows: 6 },
    tissueWebCapillaryBaseFactor: 0.24,
    tissueWebCapillaryTileScale: 0.42,
    tissueWebCapillaryAlphaMul: 1.05,
    tissueWebCapillaryAlphaFloor: 0.22,
    reactivity: {
      maxStrategicLivingAnchors: 3,
      stageOneCorruptionAnchors: 2,
      maxCorruptionAnchors: 5,
      livingInfluenceRadiusMultiplier: 3.2,
      corruptionInfluenceRadiusMultiplier: 3.8,
      conquestPulseBoost: 0.18,
    },
  },

  // World rendering
  /** Hex cell fills and everything layered from them; keep above all `background.depths`. */
  worldHexBaseDepth: 1,
  worldBorderBaseWidth: 8,
  worldBorderProgressWidth: 10,
  worldBorderGlowWidth: 4,
  worldCellShadowInset: 4,
  worldCellInnerInset: 11,
  worldCellBaseFillAlpha: 0.34,
  worldCellPulseSpeed: 1.15,
  worldCellHighlightTravelSpeed: 0.9,
  worldCellReactiveFillAlpha: 0.16,
  worldCellReactiveGlowAlpha: 0.1,
  worldCellContourAlpha: 0.13,
  worldCellPlayerInfluenceRadiusMultiplier: 1.8,
  worldCellPlayerGlowAlpha: 0.18,
  /** Hex outline colored stroke (multiplied with pulse / influence in WorldRenderer). */
  worldCellStrokeBaseAlpha: 0.46,
  /** Dark under-stroke layer alpha factor (outer rim of double stroke). */
  worldCellStrokeDarkLayerAlpha: 0.64,
  worldFillPulseDecay: 1.4,
  worldFillDisplayLerp: 0.12,
  worldBorderTrailWindow: 0.2,
  worldBorderFrontWindow: 0.045,
  expansionAnimationSeconds: 6.2,
  /** First fraction [0,1] of expansion: all hexes show thick cyan rims; rotation/reveal start after. */
  expansionCyanPrimeFraction: 0.14,
  worldStageSpacingBreath: 0.11,
  worldRevealCellMinScale: 0.36,

  // World border (GPU bloom on progress outline)
  worldBorderBloomThreshold: 0.24,
  worldBorderBloomRadius: 18,
  worldBorderBloomSteps: 4,
  worldBorderBloomAmount: 0.92,
  conquerBorderDashLengthPx: 20,
  conquerBorderGapLengthPx: 12,
  conquerBorderAnimatedWidth: 4.2,
  conquerBorderOwnedWidth: 6.4,
  conquerBorderDarkColor: 0x062033,
  conquerBorderActiveColor: 0x4ab8ff,
  conquerBorderOwnedDarkColor: 0x250508,
  conquerBorderOwnedColor: 0x8d1f29,
  conquerBorderOwnedGlowColor: 0xcf3641,
  conquerBorderOwnedCoreColor: 0xffd4d8,
  conquerBorderOwnedFillColor: 0x511117,
  conquerBorderCoreColor: 0xf5ffff,
  conquerBorderDashTravelSpeed: 42,
  conquerProgressBarWidthPx: 120,
  conquerProgressBarHeightPx: 16,
  conquerProgressBarOffsetYPx: 26,
  conquerProgressTimeColor: 0x43baff,
  conquerProgressKillColor: 0xff6a74,
  conquerProgressRailColor: 0x071118,
  conquerProgressOutlineColor: 0xd8f4ff,

  // Myriapoda FX
  myriapodaFxShellShadowColor: 0x16352e,
  myriapodaFxShellShadowAlpha: 0.22,
  myriapodaFxShellHighlightColor: 0xf1fff7,
  myriapodaFxShellHighlightAlpha: 0.11,
  myriapodaFxShellSpecColor: 0xffffff,
  myriapodaFxShellSpecAlpha: 0.08,
  myriapodaFxStomachGradientInnerColor: 0xfff1c3,
  myriapodaFxStomachGradientOuterColor: 0xff8eb9,
  myriapodaFxStomachGradientAlpha: 0.34,
  myriapodaFxStomachNoiseAlpha: 0.18,
  myriapodaFxStomachNoiseCellsX: 5,
  myriapodaFxStomachNoiseCellsY: 4,
  myriapodaFxStomachNoiseIterations: 2,
  myriapodaFxStomachNoiseWarpAmount: 0.14,
  myriapodaFxStomachNoiseFlowSpeed: 0.28,
  myriapodaFxStomachNoiseOffsetSpeedX: 0.018,
  myriapodaFxStomachNoiseOffsetSpeedY: -0.012,
  myriapodaFxStomachMaskBlurRadius: 10,
  myriapodaFxStomachMembraneGlowColor: 0xff8dbb,
  myriapodaFxStomachMembraneGlowAlpha: 0.2,
  myriapodaFxStomachMembraneInnerAlpha: 0.48,
  myriapodaFxStomachParticleGlowAlpha: 0.16,
  myriapodaFxVacuumGlowColor: 0xc8fff7,
  myriapodaFxVacuumGlowAlpha: 0.22,
  myriapodaFxVacuumCoreAlpha: 0.48,
  myriapodaFxVacuumBloomThreshold: 0.18,
  myriapodaFxVacuumBloomRadius: 14,
  myriapodaFxVacuumBloomSteps: 4,
  myriapodaFxVacuumBloomAmount: 0.64,

  // Status UI FX
  statusFxChamberGradientTopColor: 0x13343e,
  statusFxChamberGradientBottomColor: 0x2f7d8f,
  statusFxChamberGradientAlpha: 0.3,
  statusFxChamberNoiseAlpha: 0.16,
  statusFxChamberNoiseCellsX: 4,
  statusFxChamberNoiseCellsY: 5,
  statusFxChamberNoiseIterations: 2,
  statusFxChamberNoiseWarpAmount: 0.12,
  statusFxChamberNoiseFlowSpeed: 0.18,
  statusFxChamberNoiseOffsetSpeedX: 0.012,
  statusFxChamberNoiseOffsetSpeedY: -0.01,
  statusFxChamberMaskBlurRadius: 8,
  statusFxChamberGlassAlpha: 0.12,
  statusFxChamberGlowAlpha: 0.18,
  statusFxChamberParticleGlowAlpha: 0.12,
  statusFxChamberDangerWashAlpha: 0.16,

  // Transition FX
  transitionFxDurationMs: 950,
  transitionFxGradientTopColor: 0xd2fbff,
  transitionFxGradientBottomColor: 0xffc98b,
  transitionFxGradientAlpha: 0.38,
  transitionFxNoiseAlpha: 0.22,
  transitionFxNoiseCellsX: 6,
  transitionFxNoiseCellsY: 5,
  transitionFxNoiseIterations: 2,
  transitionFxNoiseWarpAmount: 0.16,
  transitionFxNoiseFlowSpeed: 0.4,
  transitionFxNoiseOffsetSpeedX: 0.03,
  transitionFxNoiseOffsetSpeedY: -0.02,
  transitionFxFlashAlpha: 0.24,
  transitionFxWipeSoftness: 0.18,

  // Enemies & hostile pickups
  targetEnemyCount: 2,
  enemyCap: 10,
  enemySpawnRadiusPadding: 40,
  jellyfishChaseForce: 0.9,
  jellyfishMaxSpeed: 1.2,
  jellyfishLinearDamping: 8.4,
  jellyfishAngularDamping: 11,
  jellyfishRadius: 12.2,
  jellyfishDisplaySize: 22.8,
  jellyfishHealth: 1,
  leechSeekForce: 2.45,
  leechMaxSpeed: 2.95,
  leechLinearDamping: 8.8,
  leechAngularDamping: 12.5,
  leechRadius: 11.4,
  leechDisplaySize: 26,
  leechHealth: 1,
  leechLatchDistancePx: 14,
  leechLatchSlotCount: 4,
  leechDrainIntervalSeconds: 1,
  leechDrainOutSeconds: 0.65,
  leechDetachRecoverySeconds: 1.35,
  leechDetachThreshold: 1,
  leechDetachMoveSpeedThreshold: 0.72,
  leechDetachMoveRate: 0.42,
  leechDetachDashImpulse: 0.88,
  leechDetachKnockbackSpeed: 2.6,
  shellbackMoveForce: 1.9,
  shellbackMaxSpeed: 1.6,
  shellbackLinearDamping: 9.4,
  shellbackAngularDamping: 13,
  shellbackRadius: 15,
  shellbackDisplaySize: 32,
  shellbackHealth: 5,
  shellbackGuardOrbitRadiusPx: 28,
  shellbackAggroRadiusPx: 96,
  shellbackExposedSeconds: 2.4,
  shellbackShelledSeconds: 1.5,
  shellbackWindupSeconds: 0.34,
  shellbackStrikeSeconds: 0.14,
  shellbackRecoverSeconds: 0.72,
  shellbackAttackCooldownSeconds: 1.3,
  shellbackClawReachPx: 54,
  shellbackStomachMaterialLoss: 15,
  shellbackRespawnDelaySeconds: 3,
  shellbackMaxActiveCount: 1,
  enemyShardScale: 1,
  enemyBurstBloomThreshold: 0.2,
  enemyBurstBloomRadius: 10,
  enemyBurstBloomSteps: 3,
  enemyBurstBloomAmount: 0.42,
  enemyBurstShardMinCount: 10,
  enemyBurstShardMaxCount: 14,
  enemyBurstBubbleMinCount: 3,
  enemyBurstBubbleMaxCount: 5,
  enemyBurstShardMinSpeedPx: 44,
  enemyBurstShardMaxSpeedPx: 104,
  enemyBurstBubbleMinSpeedPx: 16,
  enemyBurstBubbleMaxSpeedPx: 34,
  enemyBurstShardMinLifetimeSeconds: 0.48,
  enemyBurstShardMaxLifetimeSeconds: 0.68,
  enemyBurstBubbleMinLifetimeSeconds: 0.58,
  enemyBurstBubbleMaxLifetimeSeconds: 0.84,
  enemyBurstShardMinSizePx: 1.8,
  enemyBurstShardMaxSizePx: 5.2,
  enemyBurstBubbleMinSizePx: 2.2,
  enemyBurstBubbleMaxSizePx: 5.8,
  enemyBurstBubbleRisePx: 14,
  enemyBurstBubbleGrowthMinPx: 0.8,
  enemyBurstBubbleGrowthMaxPx: 2.4,
  enemyBurstShardAngularVelocity: 8.4,
  parasiteDropChance: 0.15,
  parasiteLifetimeSeconds: 20,
  parasiteConsumeIntervalSeconds: 2,

  // Limb combat
  limbCount: 4,
  limbLinks: 4,
  limbLinkLengthPx: 6,
  limbThicknessPx: 2,
  limbCooldownSeconds: 0.35,
  limbAttackIntervalSeconds: 3,
  limbAttackConeRangePx: 56,
  limbAttackConeHalfAngle: Math.PI / 4,
  limbRestReachPx: 8,
  limbAttackExtendPx: 22,
  limbExtendSeconds: 0.78,
  limbHitSeconds: 0.2,
  limbRetractSeconds: 0.74,
  limbWhipCurvePx: 13,
  limbSwayPx: 4,
  limbRootPull: 30,
  limbChainPull: 15,
  limbRecoveryPullBoost: 1.45,
  limbHomeSnapDistancePx: 2.2,
  limbDamage: 1,
  limbStrikeJitterPx: 2.8,
  limbStrikeSecondaryJitterPx: 1.9,
  limbStrikeReachPx: 16,
  limbStrikeBranchLengthPx: 13,
  limbStrikeBranchJitterPx: 2.2,
  limbStrikeTipFlashRadiusPx: 7.5,
  limbStrikeImpactFlashRadiusPx: 9.5,
  limbStrikeTipRayLengthPx: 8.5,
  limbStrikeTipRayWidthPx: 1.4,
  limbStrikeBloomThreshold: 0.14,
  limbStrikeBloomRadius: 16,
  limbStrikeBloomSteps: 4,
  limbStrikeBloomAmount: 0.86,

  // Plants
  purifiedPlantOccupancyChance: 0.8,
  plantVacuumForce: 4.4,
  plantGatherRadiusPx: 28,
  plantHexSpawnRadiusXPx: 36,
  plantHexSpawnRadiusYPx: 26,
  plantRootOffsetYPx: 18,
  plantDropScatterForceMin: 0.08,
  plantDropScatterForceMax: 0.18,
  plantDropScatterDistanceMin: 6,
  plantDropScatterDistanceMax: 14,
  fiberPlantCooldownSeconds: 18,
  fiberPlantChewSeconds: 0.85,
  fiberPlantRegrowSeconds: 1.8,
  fiberPlantSegmentLengthPx: 10,
  fiberPlantStemCount: 3,
  fiberPlantTopRadiusPx: 5.8,
  fiberPlantStemRadiusPx: 3.2,
  fiberPlantReturnForce: 3.7,
  fiberPlantUpperVacuumForceScale: 1.55,
  fiberPlantMidVacuumForceScale: 1.02,
  fiberPlantLowerVacuumForceScale: 0.52,
  fiberPlantBaseGrowthScale: 0.28,

  // Tail
  tailLengthPx: 30,
  tailRadiusPx: 3.2,
  tailMotorForce: 2.8,
  tailMotorTorque: 1.6,
  tailCorrectionFactor: 0.38,
  tailSwayPx: 8,
  tailDashSwayPx: 2.8,
  tailDashAngularSwing: 0.084,

  // Stomach
  stomachRadiusMeters: 0.64,
  stomachContainmentMarginMeters: 0.04,
  stomachNutrientCapacity: 50,
  stomachMixerAngularSpeed: 1.4,

  // Conquest
  conquerBiomassCost: 10,
  conquerOccupancySeconds: 60,
  conquerKillGoal: 10,
  conquerMaxActiveLeeches: 3,
  conquerLeechWaveMinSize: 2,
  conquerLeechWaveMaxSize: 3,
  conquerLeechAttackSpeedMultiplier: 1.16,
  conquerLeechAttackSpawnRadiusMultiplier: 1.22,
  conquerLeechAttackPackSpacingPx: 28,
  conquerLeechAttackPackJitterPx: 10,
} as const;
