export interface JellyfishDefinition {
  bobAmplitudePx: number;
  wobbleFactor: number;
  pulseSpeed: number;
  bobSpeed: number;
  bellWidthBase: number;
  bellWidthPulse: number;
  bellHeightBase: number;
  bellHeightPulse: number;
  tentacleCount: number;
  tentacleSpacingMultiplier: number;
  tentacleLengthBase: number;
  tentacleLengthSpeedBonus: number;
  tentacleSwaySpeedA: number;
  tentacleSwaySpeedB: number;
  tentacleSwayBaseA: number;
  tentacleSwaySpeedBonusA: number;
  tentacleSwayBaseB: number;
  tentacleSwaySpeedBonusB: number;
  auraColor: number;
  auraAlpha: number;
  bloomColor: number;
  bloomAlpha: number;
  tentacleGlowColor: number;
  tentacleGlowAlpha: number;
  tentacleColor: number;
  tentacleAlpha: number;
  bellColor: number;
  bellAlpha: number;
  bellHighlightColor: number;
  bellHighlightAlpha: number;
  bellOutlineColor: number;
  bellOutlineAlpha: number;
  skirtColor: number;
  skirtAlpha: number;
}

export const jellyfishDefinition: JellyfishDefinition = {
  bobAmplitudePx: 1.8,
  wobbleFactor: 0.08,
  pulseSpeed: 3.2,
  bobSpeed: 2.3,
  bellWidthBase: 0.96,
  bellWidthPulse: 0.12,
  bellHeightBase: 0.84,
  bellHeightPulse: 0.12,
  tentacleCount: 6,
  tentacleSpacingMultiplier: 0.12,
  tentacleLengthBase: 0.64,
  tentacleLengthSpeedBonus: 0.12,
  tentacleSwaySpeedA: 4.2,
  tentacleSwaySpeedB: 5.8,
  tentacleSwayBaseA: 2.4,
  tentacleSwaySpeedBonusA: 1.8,
  tentacleSwayBaseB: 1.8,
  tentacleSwaySpeedBonusB: 1.2,
  auraColor: 0xff6a84,
  auraAlpha: 0.14,
  bloomColor: 0xff9cae,
  bloomAlpha: 0.1,
  tentacleGlowColor: 0xffc2d2,
  tentacleGlowAlpha: 0.18,
  tentacleColor: 0xff7c96,
  tentacleAlpha: 0.72,
  bellColor: 0xff5b78,
  bellAlpha: 0.9,
  bellHighlightColor: 0xff9eb6,
  bellHighlightAlpha: 0.28,
  bellOutlineColor: 0xffd4de,
  bellOutlineAlpha: 0.32,
  skirtColor: 0x99293b,
  skirtAlpha: 0.76,
};
